### PR TITLE
added featured app content to Home tab

### PR DESCRIPTION
**Pull request by nlewis84**

### CODE REVIEW

**Comment by nlewis84** [comment]
Trying to figure out what is going on with my linter and tests.

**Comment by nlewis84** [comment]
I needed to add a return to the end of several files to get linter to pass.

**Comment by nlewis84** [comment]
@redreceipt Snapshots are failing. Is this not a concern here, or should I do something to address this?

**Comment by redreceipt** [comment]
what is this PR supposed to be doing?

**Comment by nlewis84** [comment]
It should update the config.yml to include featured app content

**Comment by redreceipt** [comment]
that change isn't reflected in these changes

don't worry about the linter and tests

**Comment by nlewis84** [comment]
I don't understand why the changes to config.yml show up [here](https://github.com/Differential/chase-oaks-apollos/pull/1/commits/4661ee045ad7595ba5466c596c43960bf53aa287), but not on the list of files changed?

**Comment by redreceipt** [comment]
looks like you undid the changes with your second commit

**Comment by nlewis84** [comment]
You are right! I forgot I did it to try and figure out what was going on with the linter and tests.

**Comment by redreceipt** [comment]
wanna drop a screenshot in here for me showing it working. also you can back out the linter changes so clear up the diff

**Comment by nlewis84** [comment]
simulator_screenshot_170E3510-0799-492D-900B-270CF3FA66E6
simulator_screenshot_D32DC921-7C22-454B-82CB-F7F56AFD7307

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
